export type Language = "es" | "en";

const pairs: [string, string][] = [
  ["Experiencias","Experiences"],["Qué incluye","What's included"],["Galería","Gallery"],["Reseñas","Reviews"],["Contacto","Contact"],["Cotizar mi fiesta","Plan my party"],
  ["Abrir menú","Open menu"],["Cerrar menú","Close menu"],["Tu fiesta.","Your party."],["Tu yate.","Your yacht."],["Tu mar.","Your sea."],
  ["Producimos fiestas privadas en yates donde todo está pensado para sorprender: ambiente, animación, música, anfitrionas, comida y bebidas. Tú traes a tu gente. Nosotros hacemos que la noche sea inolvidable.","We produce private yacht parties where every detail is designed to impress: atmosphere, entertainment, music, party hosts, food and drinks. You bring your favorite people. We make the night unforgettable."],
  ["Diseñar mi experiencia","Design my experience"],["Descubrir experiencias","Explore experiences"],["100% privadas","100% private"],["Servicio","Service"],["Personalizado","Tailored"],["Destino","Destination"],["Cartagena & Islas","Cartagena & Islands"],
  ["La experiencia Habib","The Habib experience"],["Creamos la fiesta privada.","We create the private party."],["Tú vienes a celebrarla.","You come to celebrate it."],
  ["Convertimos el yate en el escenario de una celebración diseñada alrededor de tu grupo, tu estilo y la energía que quieres vivir.","We turn the yacht into the setting for a celebration designed around your group, your style and the energy you want to experience."],
  ["Coordinamos anfitrionas y animadores adultos, DJ, ambientación, coctelería, catering, seguridad y cada detalle para que la fiesta fluya de principio a fin.","We coordinate adult party hosts and entertainers, DJ, styling, cocktails, catering, safety and every detail so the party flows from beginning to end."],
  ["Producción a tu medida","Tailored production"],["Todo lo que tu fiesta","Everything your party"],["necesita para brillar.","needs to shine."],
  ["Diseñamos la celebración completa y reunimos al equipo, el ambiente y los servicios que harán inolvidable tu noche en Cartagena.","We design the complete celebration and bring together the team, atmosphere and services that will make your Cartagena night unforgettable."],
  ["Experiencia insignia","Signature experience"],["Producción de","Private party"],["fiestas privadas","production"],["Concepto, música, ambientación y coordinación completa para crear una fiesta extraordinaria a bordo.","Concept, music, styling and full coordination to create an extraordinary party on board."],["Quiero celebrar","I want to celebrate"],
  ["Animación y","Entertainment and"],["anfitrionas","party hosts"],["Animadores y anfitrionas adultas, seleccionados según el estilo de tu grupo para mantener la mejor energía.","Adult entertainers and party hosts selected to match your group's style and keep the energy high."],["Crear el ambiente","Set the atmosphere"],
  ["Catering y","Catering and"],["barra premium","premium bar"],["Menús, pasabocas, coctelería y bebidas elegidos para acompañar el ritmo y el estilo de tu celebración.","Menus, canapés, cocktails and drinks chosen to match the pace and style of your celebration."],["Diseñar el menú","Design the menu"],
  ["Nos ocupamos de todo","We take care of everything"],["Detalles impecables.","Impeccable details."],["Cero preocupaciones.","Zero worries."],["Producimos tu fiesta de principio a fin para que solo tengas que llegar, brindar y disfrutar con tus invitados.","We produce your party from beginning to end, so all you have to do is arrive, raise a glass and enjoy it with your guests."],
  ["Yate elegido para tu fiesta","Yacht selected for your party"],["Capitán y tripulación","Captain and crew"],["Anfitrionas y animadores","Party hosts and entertainers"],["DJ y sistema de sonido","DJ and sound system"],["Decoración personalizada","Custom styling"],["Menú y catering","Menu and catering"],["Bebidas y coctelería","Drinks and cocktails"],["Coordinación del evento","Event coordination"],["Personalizar mi plan","Customize my plan"],
  ["Así de fácil","It's this easy"],["Del primer mensaje","From the first message"],["al momento perfecto.","to the perfect moment."],["Cuéntanos tu idea","Tell us your idea"],["Fecha, invitados, ocasión y el tipo de ambiente que quieres vivir.","Your date, guests, occasion and the kind of atmosphere you want."],["Producimos tu fiesta","We produce your party"],["Creamos el concepto y coordinamos yate, animación, música, catering y bebidas.","We create the concept and coordinate the yacht, entertainment, music, catering and drinks."],["Confirma y celebra","Confirm and celebrate"],["Reserva tu fecha y llega listo para disfrutarlo todo.","Reserve your date and arrive ready to enjoy it all."],
  ["Momentos Habib","Habib moments"],["Cartagena se vive","Cartagena is best"],["mejor desde el mar.","experienced from the sea."],
  ["Lo que dicen nuestros invitados","What our guests say"],["Recuerdos que siguen","Memories that keep"],["brillando después.","shining afterwards."],["Experiencias memorables","Memorable experiences"],
  ["“Habib entendió exactamente lo que queríamos. El montaje, la música y la atención fueron increíbles. Se sintió exclusivo de principio a fin.”","“Habib understood exactly what we wanted. The setup, music and service were incredible. It felt exclusive from beginning to end.”"],
  ["“La mejor noche de nuestro viaje a Cartagena. El yate era espectacular y no tuvimos que preocuparnos por absolutamente nada.”","“The best night of our Cartagena trip. The yacht was spectacular and we didn't have to worry about a single thing.”"],
  ["“Organizaron nuestra cena a bordo con muchísimo gusto. La comida, el atardecer y cada detalle superaron lo que imaginábamos.”","“They arranged our dinner on board beautifully. The food, sunset and every detail exceeded what we imagined.”"],
  ["Cumpleaños privado","Private birthday"],["Fiesta en la bahía","Bay party"],["Cena especial","Special dinner"],
  ["“La tripulación fue muy atenta y la ruta por las islas fue preciosa. Todo estaba listo cuando llegamos.”","“The crew was very attentive and the island route was beautiful. Everything was ready when we arrived.”"],["Día en las islas","Island day"],
  ["“Celebramos la despedida de mi hermana y fue perfecta. Buena música, cocteles y un servicio excelente.”","“We celebrated my sister's bachelorette party and it was perfect. Great music, cocktails and excellent service.”"],["Despedida privada","Private bachelorette"],
  ["“Habib armó una fiesta increíble para nuestro grupo. La música, las anfitrionas y el servicio mantuvieron el ambiente arriba toda la noche.”","“Habib put together an incredible party for our group. The music, party hosts and service kept the energy high all night.”"],["Fiesta con amigos","Party with friends"],
  ["“La propuesta de matrimonio salió mejor de lo que soñé. Cuidaron cada detalle y el atardecer fue mágico.”","“The proposal turned out better than I dreamed. They took care of every detail and the sunset was magical.”"],["Propuesta a bordo","Proposal on board"],
  ["“Una experiencia impecable desde la salida hasta el regreso. Sin duda lo repetiríamos en Cartagena.”","“An impeccable experience from departure to return. We would definitely do it again in Cartagena.”"],["Celebración con amigos","Celebration with friends"],["Reseñas de clientes","Customer reviews"],
  ["Tu celebración empieza aquí","Your celebration starts here"],["Hablemos de","Let's talk about"],["tu próximo momento.","your next moment."],["Cuéntanos cómo imaginas la fiesta. Habib organizará el ambiente, el entretenimiento, el catering, las bebidas y todo lo necesario para hacerla realidad.","Tell us how you imagine the party. Habib will organize the atmosphere, entertainment, catering, drinks and everything needed to make it happen."],
  ["WhatsApp directo","Direct WhatsApp"],["Ubicación","Location"],["Atención","Availability"],["Todos los días","Every day"],["Nombre completo","Full name"],["Fecha del evento","Event date"],["Número de invitados","Number of guests"],["Tipo de experiencia","Experience type"],["Selecciona una opción","Select an option"],["Fiesta privada en yate","Private yacht party"],["Fiesta con animación y anfitrionas","Party with entertainment and hosts"],["Catering y bebidas a bordo","Catering and drinks on board"],["Otra celebración privada","Another private celebration"],["Enviar por WhatsApp","Send via WhatsApp"],
  ["WhatsApp abierto. Envía el mensaje para completar tu solicitud.","WhatsApp is open. Send the message to complete your request."],["Al enviar, abriremos WhatsApp con los datos de tu solicitud.","When you submit, we'll open WhatsApp with your request details."],
  ["Producción de fiestas privadas en yates en Cartagena de Indias.","Private yacht party production in Cartagena de Indias."],["Todos los derechos reservados.","All rights reserved."],["Habla con Habib","Chat with Habib"],["Hablar con Habib por WhatsApp","Chat with Habib on WhatsApp"],["Tu nombre","Your name"],["Ej. 12","E.g. 12"],["¿Qué quieres celebrar? ¿Tienes alguna idea especial?","What would you like to celebrate? Do you have a special idea?"],
  ["Fiesta privada nocturna en un yate frente a Cartagena","Private night yacht party overlooking Cartagena"],["Anfitrionas adultas animando una fiesta privada en un yate en Cartagena","Adult party hosts entertaining guests at a private yacht party in Cartagena"],["Cena y celebración privada a bordo de un yate","Private dinner and celebration aboard a yacht"],["Fiesta privada producida por Tours Habib con animación, coctelería y catering","Private party produced by Tours Habib with entertainment, cocktails and catering"],["Amigos celebrando al atardecer en un yate en Cartagena","Friends celebrating at sunset on a yacht in Cartagena"],["Fiesta nocturna en yate con Cartagena iluminada","Night yacht party with Cartagena illuminated"],["Yate navegando en aguas del Caribe","Yacht cruising Caribbean waters"]
];

const esToEn = Object.fromEntries(pairs);
const enToEs = Object.fromEntries(pairs.map(([es,en]) => [en,es]));
function translated(value: string, language: Language) {
  const dictionary = language === "en" ? esToEn : enToEs;
  const leading = value.match(/^\s*/)?.[0] ?? "", trailing = value.match(/\s*$/)?.[0] ?? "", core = value.trim();
  return core && dictionary[core] ? `${leading}${dictionary[core]}${trailing}` : value;
}
export function translatePage(language: Language) {
  document.documentElement.lang = language;
  document.title = language === "en" ? "Tours Habib | Private Yacht Parties in Cartagena" : "Tours Habib | Fiestas Privadas en Yates en Cartagena";
  const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT);
  let node = walker.nextNode();
  while(node){ node.nodeValue = translated(node.nodeValue ?? "", language); node = walker.nextNode(); }
  document.querySelectorAll<HTMLElement>("[placeholder],[aria-label],[alt]").forEach(el => ["placeholder","aria-label","alt"].forEach(attr => { const value=el.getAttribute(attr); if(value) el.setAttribute(attr,translated(value,language)); }));
}
